language: cpp

services:
  - docker

addons:
  apt:
    packages:
      - libpcap-dev
      - libssl-dev

branches:
  only:
  - master

notifications:
  email:
    recipients:
    - bro-commits-internal@bro.org

# Build Bro and run tests in the following Linux distros (specifying "travis"
# builds bro in Travis without using docker).
env:
  - distro: centos_7
  - distro: debian_9
  - distro: fedora_28
  - distro: ubuntu_16.04
  - distro: ubuntu_18.04

install: sh testing/scripts/travis-job install $distro

before_script: sh testing/scripts/travis-job build $distro

script: sh testing/scripts/travis-job run $distro
